// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"MikuMikuCloudDrive/config"
	"MikuMikuCloudDrive/core"
	"MikuMikuCloudDrive/services"
)

// Injectors from wire.go:

// InitializeApp 生成 ServiceContext 和 AppConfig 实例
func InitializeApp() (*services.ServiceContext, error) {
	db := core.InitGorm()
	client := core.InitRedis()
	configConfig := config.ReadAllConfig()
	serviceContext := services.NewServiceContext(db, client, configConfig)
	return serviceContext, nil
}
