[app]
title = "MikuMikuCloudDrive"
version = "0.0.1"
server = "0.0.0.0"
port = 8080
upload_dir = "uploads"
cache_dir = "cache"
[mysql]
host = "127.0.0.1"
port = 3306
username = "root"
password = "123456"
database = "mikumiku_cloud_drive"
[auth]
auth_secret = "meowrain"
expire_time = 1 # 1天后过期