definitions:
  login_types.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  login_types.LoginResponse:
    properties:
      token:
        type: string
    type: object
  logout_types.LogoutRequest:
    properties:
      token:
        type: string
    type: object
  logout_types.LogoutResponse:
    type: object
  resgister_types.RegisterRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  resgister_types.RegisterResponse:
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  userinfo_types.UpdateUserInfoRequest:
    properties:
      avatar:
        description: 绑定到 JSON 字段
        type: string
      email:
        description: 绑定到 JSON 字段
        type: string
      password:
        description: 绑定到 JSON 字段
        type: string
      token:
        description: 绑定到 Authorization 头
        type: string
      username:
        description: 绑定到 JSON 字段
        type: string
    type: object
  userinfo_types.UpdateUserInfoResponse:
    type: object
  userinfo_types.UserInfoRequest:
    properties:
      token:
        type: string
    type: object
  userinfo_types.UserInfoResponse:
    properties:
      avatar:
        type: string
      email:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /user/info:
    get:
      consumes:
      - application/json
      description: 用户信息获取接口
      parameters:
      - description: 注册请求参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/userinfo_types.UserInfoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 状态码为200 表示成功返回
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/userinfo_types.UserInfoResponse'
              type: object
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/response.Response'
        "502":
          description: 服务内部错误
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取用户信息 API(获取用户信息)
      tags:
      - 用户管理
    put:
      consumes:
      - application/json
      description: 更新用户信息接口
      parameters:
      - description: 注册请求参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/userinfo_types.UpdateUserInfoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 状态码为200 表示成功返回
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/userinfo_types.UpdateUserInfoResponse'
              type: object
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/response.Response'
        "502":
          description: 服务内部错误
          schema:
            $ref: '#/definitions/response.Response'
      summary: 更新用户信息 API(更新用户信息)
      tags:
      - 用户管理
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登录接口
      parameters:
      - description: 登录请求参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/login_types.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功返回
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/login_types.LoginResponse'
              type: object
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/response.Response'
        "502":
          description: 服务内部错误
          schema:
            $ref: '#/definitions/response.Response'
      summary: Login API(登录接口)
      tags:
      - 用户管理
  /user/logout:
    post:
      consumes:
      - application/json
      description: 用户登录接口
      parameters:
      - description: 登录请求参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/logout_types.LogoutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 状态码为200 表示成功返回
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/logout_types.LogoutResponse'
              type: object
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/response.Response'
        "502":
          description: 服务内部错误
          schema:
            $ref: '#/definitions/response.Response'
      summary: Logout API(注销接口)
      tags:
      - 用户管理
  /user/register:
    post:
      consumes:
      - application/json
      description: 用户注册接口
      parameters:
      - description: 注册请求参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/resgister_types.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 状态码为200 表示成功返回
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/resgister_types.RegisterResponse'
              type: object
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/response.Response'
        "502":
          description: 服务内部错误
          schema:
            $ref: '#/definitions/response.Response'
      summary: Register API(注册接口)
      tags:
      - 用户管理
swagger: "2.0"
